;;; stock-ticker-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stock-ticker.el

(let ((loads (get 'stock-ticker 'custom-loads))) (if (member '"stock-ticker" loads) nil (put 'stock-ticker 'custom-loads (cons '"stock-ticker" loads)) (put 'applications 'custom-loads (cons 'stock-ticker (get 'applications 'custom-loads)))))
(defvar stock-ticker-symbols '("^gspc" "^dji" "^ixic" "^tnx" "^nya" "XAUUSD=X" "EURUSD=X") "\
List of ticker symbols that the mode line will cycle through.")
(custom-autoload 'stock-ticker-symbols "stock-ticker" t)
(defvar stock-ticker-update-interval 300 "\
Number of seconds between rest calls to fetch data.")
(custom-autoload 'stock-ticker-update-interval "stock-ticker" t)
(defvar stock-ticker-display-interval 10 "\
Number of seconds between refreshing the mode line.")
(custom-autoload 'stock-ticker-display-interval "stock-ticker" t)
(defvar stock-ticker-global-mode nil "\
Non-nil if Stock-Ticker-Global mode is enabled.
See the `stock-ticker-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `stock-ticker-global-mode'.")
(custom-autoload 'stock-ticker-global-mode "stock-ticker" nil)
(autoload 'stock-ticker-global-mode "stock-ticker" "\
Add stock ticker info to the mode line.

Enabeling stock ticker global mode will add stock information in the form
SYMBOL: PRICE CHANGE (PERCENT CHANGE) to the mode line for each stock symbol
listed in 'stock-ticker-symbols'. Only one symbol is displayed at a time and
the mode cycles through the requested symbols at a configurable interval.

This is a global minor mode.  If called interactively, toggle the
`Stock-Ticker-Global mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='stock-ticker-global-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "stock-ticker" '("stock-ticker--"))

;;; End of scraped data

(provide 'stock-ticker-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stock-ticker-autoloads.el ends here
