;;; wordnut-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wordnut.el

(autoload 'wordnut-search "wordnut" "\
Prompt for a word to search for, then do the lookup.

(fn WORD)" t)
(autoload 'wordnut-lookup-current-word "wordnut" nil t)
(register-definition-prefixes "wordnut" '("wordnut-"))


;;; Generated autoloads from wordnut-history.el

(register-definition-prefixes "wordnut-history" '("wordnut--h-"))


;;; Generated autoloads from wordnut-u.el

(register-definition-prefixes "wordnut-u" '("wordnut-u-"))

;;; End of scraped data

(provide 'wordnut-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wordnut-autoloads.el ends here
